"""add surname

Revision ID: 514d55fb4f0e
Revises: 56390ad029b3
Create Date: 2024-03-14 17:21:31.758975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514d55fb4f0e'
down_revision = '56390ad029b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=32), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
